version: "3.8"

services:
  task_tracking_service:
    build: ./
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - task_tracking_db_postgres
    environment:
      - APP_PORT=8081
      - DB_HOST=task_tracking_db_postgres
      - DB_PORT=5433
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=task_tracking_db
      - DB_SSL_MODE=disable

  task_tracking_db_postgres:
    image: postgres
    container_name: task_tracking_db_postgres
    restart: always

    shm_size: 256mb

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_tracking_db

    ports:
      - "5433:5432"
